services:
  db:
    image: mongo
    container_name: db
    ports:
      - "4000:27017"
    restart: always
  express-mongo:
    image: express-mongo
    build: 
      context: ./db/mongodb
      dockerfile: Dockerfile
    container_name: express-mondo
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - URI=mongodb://localhost:4000
    restart: 'no'